version: '3.3'

services:
  wrf-runs:
    build:
      context: ../
      dockerfile: gfortran_wvt_mr/Dockerfile
    image: mullenkamp/wrf-auto-runs-wvt-mr:1.0
    shm_size: '1gb'
    volumes:
        - "./parameters.toml:/app/parameters.toml"
        - ~/WPS_GEOG:/WPS_GEOG
